baseURL = "https://blog.felipevaldez.com/"
languageCode = "en"
defaultContentLanguage = "en"
title = "Felipe Valdez - Blog"
theme = "blowfish"
enableRobotsTXT = true

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]

[services]
  [services.googleAnalytics]
    ID = "G-RC52W8J799"