title = "Felipe Valdez - Blog"
languageCode = "es"

[params]
  displayName = "Español"
  isoCode = "es"

  [params.author]
    name = "Felipe Valdez"
    image = "img/avatar.jpg"
    headline = "Geógrafo | Especialista en SIG | Cartografía para la Justicia Social"
    bio = "Geógrafo urbano y económico utilizando SIG y cartografía para la Justicia Social."
    links = [
      { email = "mailto:felipemiguelvaldez@gmail.com" },
      { linkedin = "https://www.linkedin.com/in/felipevaldez/" },
      { github = "https://github.com/fmvaldezg" },
      { google-scholar = "https://scholar.google.com/citations?user=VC2gTN0AAAAJ&hl=en" },
      { link = "https://felipevaldez.com" },
    ]