title = "Felipe Valdez - Blog"

[params]
  displayName = "English"
  isoCode = "en"

  [params.author]
    name = "Felipe Valdez"
    image = "img/avatar.jpg"
    headline = "Geographer | GIS Specialist | Mapping for Social Justice"
    bio = "Urban and economic geographer leveraging GIS and mapping for Social Justice."
    links = [
      { email = "mailto:felipemiguelvaldez@gmail.com" },
      { linkedin = "https://www.linkedin.com/in/felipevaldez/" },
      { orcid = "https://orcid.org/0000-0001-6999-5657" },
      { google-scholar = "https://scholar.google.com/citations?user=VC2gTN0AAAAJ&hl=en" },
      { link = "https://felipevaldez.com" },
      { bluesky = "https://bsky.app/profile/fmvaldez" },
    ]
