title = "Felipe Valdez - Blog"

[params]
  displayName = "English"
  isoCode = "en"

  [params.author]
    name = "Felipe Valdez"
    image = "img/avatar.jpg"
    headline = "Geographer | GIS Specialist | Mapping for Social Impact"
    bio = "Urban and economic geographer leveraging GIS and mapping for community development."
    links = [
      { email = "mailto:felipemiguelvaldez@gmail.com" },
      { linkedin = "https://www.linkedin.com/in/felipevaldez/" },
      { github = "https://github.com/fmvaldezg" },
      { google-scholar = "https://scholar.google.com/citations?user=VC2gTN0AAAAJ&hl=en" },
      { link = "https://felipevaldez.com" },
    ]
